dependencies {

    api("com.github.GTNewHorizons:GTNHLib:0.11.48:dev")
    implementation("com.github.GTNewHorizons:GTNHExtLib:1.0.4:dev")

    compileOnly("com.github.GTNewHorizons:NotEnoughItems:2.8.140-GTNH:dev")
    runtimeOnlyNonPublishable("com.github.GTNewHorizons:NotEnoughItems:2.8.140-GTNH:dev")

    compileOnlyApi("com.github.GTNewHorizons:CodeChickenCore:1.4.19:dev") { transitive = false }
    runtimeOnlyNonPublishable("com.github.GTNewHorizons:CodeChickenCore:1.4.19:dev")

    compileOnly("com.github.GTNewHorizons:InventoryBogoSorter:1.3.50-GTNH:dev") { transitive = false }
    runtimeOnlyNonPublishable("com.github.GTNewHorizons:InventoryBogoSorter:1.3.50-GTNH:dev")
    compileOnly("com.github.GTNewHorizons:MouseTweaks:2.5.3-GTNH:dev") { transitive = false }
    runtimeOnlyNonPublishable("com.github.GTNewHorizons:MouseTweaks:2.5.3-GTNH:dev")
    compileOnly("com.github.GTNewHorizons:ModularUI2:2.3.85-1.7.10:dev") { transitive = false }
    compileOnly("com.github.GTNewHorizons:ServerUtilities:2.4.10:dev") { transitive = false }
    runtimeOnlyNonPublishable("com.github.GTNewHorizons:ServerUtilities:2.4.10:dev")

    compileOnly("com.github.GTNewHorizons:waila:1.19.34:dev")
    runtimeOnlyNonPublishable("com.github.GTNewHorizons:waila:1.19.34:dev")

    compileOnly("com.github.GTNewHorizons:Applied-Energistics-2-Unofficial:rv3-beta-1040-GTNH:dev")
    runtimeOnlyNonPublishable("com.github.GTNewHorizons:Applied-Energistics-2-Unofficial:rv3-beta-1040-GTNH:dev")

    compileOnly("thaumcraft:Thaumcraft:1.7.10-4.2.3.5:dev")
    runtimeOnlyNonPublishable("thaumcraft:Thaumcraft:1.7.10-4.2.3.5:dev") { transitive = false }

    compileOnly("com.github.GTNewHorizons:ThaumicEnergistics:1.7.60-GTNH:dev") { transitive = false }
    runtimeOnlyNonPublishable("com.github.GTNewHorizons:ThaumicEnergistics:1.7.60-GTNH:dev") { transitive = false }

    runtimeOnlyNonPublishable("ganymedes01.etfuturum:Et-Futurum-Requiem:2.6.59-GTNH")
    runtimeOnlyNonPublishable("com.github.GTNewHorizons:Baubles-Expanded:2.2.23-GTNH:dev")
    runtimeOnlyNonPublishable("curse.maven:cofh-core-69162:2388751")
    runtimeOnlyNonPublishable("it.unimi.dsi:fastutil:8.5.18")

    // jvmDowngrader
    compileOnly("javax.xml.bind:jaxb-api:2.3.1")
    compileOnly("org.jetbrains:annotations:26.0.1")
    compileOnly("org.projectlombok:lombok:1.18.42") { transitive = false }
    annotationProcessor("org.projectlombok:lombok:1.18.42")

    implementation("com.google.auto.value:auto-value-annotations:1.10.4")
    annotationProcessor("com.google.auto.value:auto-value:1.10.4")
}

configurations.configureEach {
    exclude group: "com.github.GTNewHorizons", module: "CodeChickenLib"
    exclude group: "com.github.GTNewHorizons", module: "Hodgepodge"
    exclude group: "com.github.GTNewHorizons", module: "Baubles"
}

// deps may transitively add Baubles, so we replace it
project.getConfigurations()
        .all(c -> {
            final DependencySubstitutions ds = c.getResolutionStrategy()
                    .getDependencySubstitution();
            ds.substitute(ds.module("com.github.GTNewHorizons:Baubles"))
                    .using(ds.module("com.github.GTNewHorizons:Baubles-Expanded:2.2.23-GTNH"))
                    .withClassifier("dev")
                    .because("Baubles-Expanded replaces Baubles");
        });

